### ISSUE TITLE
Prolike - get an account on hub.docker.com

### ISSUE THREAD

**Issue by lakruzz** [prolike/vhhr#2]
Create an automated build on the fork we created `prolike/youtransfer`

**Comment by LouBNielsen** [comment]
Can't get further :/ ... 

Tried to create an account with prolike mail

![image](https://user-images.githubusercontent.com/17924001/40425265-31794a34-5e98-11e8-9c66-8b0c1c5a3e3c.png)

**Comment by lakruzz** [comment]
What email was it sent to @loubnielsen?

**Comment by LouBNielsen** [comment]
@lakruzz
prolike@prolike.io

**Comment by lakruzz** [comment]
OK @LouBNielsen Is there a password we need to store somewhere then?

**Comment by lakruzz** [comment]
OK, it's just connected to our prolike account a t GitHub
